version: '2'

services:
  sogo:
#   if you want to build your own image
    build: 
      context: .
      args:
        - version=3.2.10

#     if you want to use builded image, uncomment next line
#     image: sheogorath/sogo:3.2
    volumes:
#     replace by the path to your own sogo.conf file
      - ./../sogo.conf:/etc/sogo/sogo.conf
    environment:
      - "TZ=Europe/Amsterdam"
    networks:
      - database
      - memcache
      - frontend
  db:
    image: postgres:9.5
    networks:
      - database
  memcached:
    image: memcached:1.4-alpine
    network:
      - memcache
  nginx:
    image: nginx
    networks:
      - frontend
    volumes_from:
      - sogo:ro
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  database:
    internal: true
  memcache:
    internal: true
  frontend:
